### ISSUE TITLE
Infer fails with "PCH file built from a different branch ((clang-800.0.42.1)) than the compiler ()"

### ISSUE THREAD

**Issue by michaeleiselsc** [facebook/infer#590]
Hi, I'm getting the following problem:

```
▸ Build Succeeded
Capturing using xcpretty...
Starting translating 1 files 
error: PCH file built from a different branch ((clang-800.0.42.1)) than the compiler ()
1 error generated.
Error: the following clang command did not run successfully:
  '/usr/local/Cellar/infer/0.9.5/lib/infer/facebook-clang-plugins/clang/install/bin/clang' "@/Users/michael/Developer/Snapchat/Dev/phantom2/infer-out/clang/clang_command_ebab2d.txt"
..
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

Found 0 source files in ...
```

Any ideas?

**Comment by michaeleiselsc** [comment]
I believe this may have been caused by me building it from scratch without using infer, and then having infer do an incremental build? But then there are problems when I try to do it with infer from scratch

**Comment by michaeleiselsc** [comment]
```
$ /usr/bin/clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
/usr/local/Cellar/infer/0.9.5/lib/infer/facebook-clang-plugins/clang/install/bin
```
```
$ /usr/local/Cellar/infer/0.9.5/lib/infer/facebook-clang-plugins/clang/install/bin/clang --version
clang version 4.0.0 
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /usr/local/Cellar/infer/0.9.5/lib/infer/facebook-clang-plugins/clang/install/bin/.
```

**Comment by michaeleiselsc** [comment]
what if i just replaced infer's version of clang with a symlink to xcode's?

**Comment by jvillard** [comment]
Can you try with PCH disabled? `GCC_PRECOMPILE_PREFIX_HEADER=NO infer -- ...` (see our [FAQ](http://fbinfer.com/support.html#i-get-a-compilation-error-involving-pch-files-when-running-infer)).

> But then there are problems when I try to do it with infer from scratch

What problems? I don't think it will work incrementally if you first compiled with Apple's clang.

> what if i just replaced infer's version of clang with a symlink to xcode's?

Infer needs a specific version of clang to run which is why it's shipped with infer. This is because it attaches a plugin to clang to read its AST, and this requires to be used with the same version of clang than the version that the plugin was compiled for.

**Comment by jvillard** [comment]
Closing optimistically in case `GCC_PRECOMPILE_PREFIX_HEADER=NO` fixed it for you. Please reopen if not.

**Comment by sencho** [comment]
@jvillard the problem is still alive!Every time I have to delete the derivedData folder  to return normal,and i try add `GCC_PRECOMPILE_PREFIX_HEADER=NO`,but can not fix it.
```
Starting translating 1988 files 
.................................................................................................................................................error: PCH file built from a different branch ((clang-802.0.42)) than the compiler ()
1 error generated.
Error: the following clang command did not run successfully:
  '/usr/local/Cellar/infer/0.12.0/lib/infer/facebook-clang-plugins/clang/install/bin/clang' "@/Users/sencho/Code/CSMBP-iOS/builds/5f6403d1/0/iOS/CSMBP-iOS/infer-out/clang/clang_command_afce43.txt"
...error: PCH file built from a different branch ((clang-802.0.42)) than the compiler ()
1 error generated.
```

**Comment by jvillard** [comment]
@sencho what's the command line you are using?

**Comment by sencho** [comment]
@jvillard 
```
Infer capture – xcodebuild ……
```

**Comment by jvillard** [comment]
@sencho can you please give the full command including `GCC_PRECOMPILE_PREFIX_HEADER=NO` where you get the error above?

**Comment by sencho** [comment]
@jvillard,here is my whole CI script

```yaml
stages:
  - build
  - analyse

cache:
  paths:
  - infer-out/

build_capture:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build
  script:
    - xcodebuild -workspace demo.xcworkspace -scheme demo -sdk iphonesimulator10.3 -configuration Release clean | xcpretty
    - infer capture -- xcodebuild -workspace demo.xcworkspace -scheme demo -sdk iphonesimulator10.3 -configuration Release build
  only:
    - master
  tags:
    - infer-capture

analyse:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: analyse
  script:
    - infer -- analyze
  only:
    - master
  tags:
    - infer-analyze
```
